# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://LukeBetham.github.io/stonehaven_tools/"

git_url = "https://github.com/LukeBetham/stonehaven_tools/tree/Master/"

def custom_doc_links(name): return None
