# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://LukeBetham.github.io/stonehaventools/"

git_url = "https://github.com/LukeBetham/stonehaventools/tree/Master/"

def custom_doc_links(name): return None
